### ISSUE TITLE
Can't `cd` into external hard drive

### ISSUE THREAD

**Issue by Lucaslah** [termyapp/Termy#28]
When running the `cd` command, You can't change into a folder like: `/Volumes/HHD/Folder`

**Error**
It gives the following error:
```javascript
is not a valid directory
```

**Comment by martonlanga** [comment]
@Lucaslah You can also change dirs without the `cd` command. Start typing the dir name, press <kbd>Tab</kbd> to autocomplete and <kbd>Enter</kbd>. Does it work that way?

Have only tested `cd` with paths above the home dir, will fix with #18

**Comment by Lucaslah** [comment]
@martonlanga Yeah I know, I dose not matter if I use `cd` or not anyway I try I can not change to the `Volumes` folder on macOS

**Comment by martonlanga** [comment]
Just released [`v0.1.4`](https://github.com/termyapp/Termy/releases/download/v0.1.4/Termy-0.1.4.dmg), it should work now!

**Comment by Lucaslah** [comment]
OK, thanks Ill try it now.
