### ISSUE TITLE
Is it possible to open the remote host through ssh and get auto-completion?

### ISSUE THREAD

**Issue by YU5Z8X2CvH1fv4ep** [TermyApp/termy#95]
Is it possible to open the remote host through ssh and get auto-completion

**Comment by YU5Z8X2CvH1fv4ep** [comment]
It is not necessary to use the "ssh" command

**Comment by martonlanga** [comment]
It's not possible currently. Could be achieved in the future similar to how [VSCode made remote development work](https://code.visualstudio.com/blogs/2019/05/02/remote-development).
